### PR TITLE
sqlglot 23.7.0 (with updated pin)

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

References:
- includes #397 
- includes same fix as #398

Changes:
- updates `sqlglotrs` pin

Future work:
- probably need to go back and do a historical `repodata-patches` to align the versions correctly

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
This is also ready, but shouldn't be merged until after #398

**Comment by thewchan** [comment]
@bollwyvl oops I think I fixed this in a parallel bot PR, but let me know if this still needs to be merged

**Comment by bollwyvl** [comment]
> let me know if this still needs to be merged

please see #398

**Comment by thewchan** [comment]
got it okay I can merge that one, but then this one wouldn't need to be merged right?

**Comment by bollwyvl** [comment]
> this one wouldn't need to be merged right?

no, provided the versions line up, the bot can be asked to redo #397

**Pull request closed without merging**
